Repository googleinterns/step26-2020, pull requests merged in 2020-07, with the labels that each got.

#2 Mockup Schedule Page (prototype draft 01)
  src/main/webapp/src/app/app-routing.module.ts
  src/main/webapp/src/app/app.component.html
  src/main/webapp/src/app/app.module.ts
  src/main/webapp/src/app/schedule-page/schedule-page.component.css
  src/main/webapp/src/app/schedule-page/schedule-page.component.html
  src/main/webapp/src/app/schedule-page/schedule-page.component.spec.ts
  src/main/webapp/src/app/schedule-page/schedule-page.component.ts
Labels: prototype

#11 Find Gardens Page
  package-lock.json
  package.json
  src/main/webapp/angular.json
  src/main/webapp/package-lock.json
  src/main/webapp/package.json
  src/main/webapp/src/app/app-routing.module.ts
  src/main/webapp/src/app/app.module.ts
  src/main/webapp/src/app/find-gardens-page/find-gardens.component.css
  src/main/webapp/src/app/find-gardens-page/find-gardens.component.html
  src/main/webapp/src/app/find-gardens-page/find-gardens.component.spec.ts
  src/main/webapp/src/app/find-gardens-page/find-gardens.component.ts
Labels: MVP, prototype

#12 Add top bar to GrowPod
  src/main/webapp/src/app/app.component.html
  src/main/webapp/src/app/app.component.ts
  src/main/webapp/src/app/common/growpod-page-styles.css
  src/main/webapp/src/app/common/material-components.ts
Labels: MVP, prototype

#13 My Gardens Page
  src/main/webapp/src/app/app-routing.module.ts
  src/main/webapp/src/app/app.module.ts
  src/main/webapp/src/app/common/growpod-page-styles.css
  src/main/webapp/src/app/my_gardens_page/my-gardens.component.css
  src/main/webapp/src/app/my_gardens_page/my-gardens.component.html
  src/main/webapp/src/app/my_gardens_page/my-gardens.component.spec.ts
  src/main/webapp/src/app/my_gardens_page/my-gardens.component.ts
Labels: MVP, prototype

#14 Create Gardens Form
  package-lock.json
  package.json
  src/main/webapp/src/app/app-routing.module.ts
  src/main/webapp/src/app/app.module.ts
  src/main/webapp/src/app/common/growpod-page-styles.css
  src/main/webapp/src/app/create-gardens-form/create-gardens.component.css
  src/main/webapp/src/app/create-gardens-form/create-gardens.component.html
  src/main/webapp/src/app/create-gardens-form/create-gardens.component.spec.ts
  src/main/webapp/src/app/create-gardens-form/create-gardens.component.ts
  src/main/webapp/src/app/find-gardens-page/find-gardens.component.css
  src/main/webapp/src/app/find-gardens-page/find-gardens.component.ts
Labels: MVP, prototype

#32 [npm & gapi] Google Calendar API Setup
  .bashrc
  .gitignore
  package-lock.json
  package.json
  src/main/webapp/src/app/app.module.ts
  src/main/webapp/src/app/calendar-task/task.component.css
  src/main/webapp/src/app/calendar-task/task.component.html
  src/main/webapp/src/app/calendar-task/task.component.ts
  src/main/webapp/src/app/common/growpod-page-styles.css
  src/main/webapp/src/app/datepicker/datepicker.component.html
  src/main/webapp/src/app/datepicker/datepicker.component.ts
  src/main/webapp/src/app/schedule-page/schedule-page.component.css
  src/main/webapp/src/app/schedule-page/schedule-page.component.html
  src/main/webapp/src/app/schedule-page/schedule-page.component.ts
  src/main/webapp/src/environments/environment.prod.ts
  src/main/webapp/src/environments/environment.ts
  src/main/webapp/src/index.html
  src/main/webapp/src/main.ts
  src/main/webapp/src/sessions/gapi.session.ts
  src/main/webapp/tsconfig.app.json
  src/main/webapp/tsconfig.json
  src/main/webapp/tslint.json
Labels: MVP, calendar development
